#!/bin/bash

#Config File
CONFIG=./sshcon.cfg

connect()
{
    if [ $1 ]
    then
        #Split the line in config to host and ip
        while IFS="=" read -r host ip
        do 
            if [ $1 == $host ]
            then
                echo "Host $host found"
                echo "Attempting to connect to $ip"
                break
            fi
        done < $CONFIG
        #If the host exists in the config SSH to the ip
        if [ ! -z $ip ]
        then
            ssh $ip
        else
            echo "Host doesn't exist"
        fi

    fi
}

list()
{
    header=" %-10s %8s\n"
    format=" %-10s %08s\n"

    printf "$header" "HOST" "IP ADDRESS"

    while IFS="=" read -r host ip
    do 
        printf "$format" \
        $host $ip 
    done < $CONFIG
}

help()
{
    printf "Usage: sshcon [OPTION]... [HOST]...\n"
    printf " %s %s %s\n" \
    "-h," "--help" "display this help menu" \
    "-l," "--list" "show a list of the hosts from the config file"
}

while :
do
case $1 in
    -h|--help)
        help
        exit
        ;;
    -l|--list)
        list
        exit
        ;;
    -?*)
        echo "Unknown option: $1"
        break
        ;;
    *)
        if [ ! -z $1 ]
        then
            connect $1
        else
            help
        fi
        break
        ;;
esac
done



