#!/bin/bash

#Config File
CONFIG=~/.config/sshcon/hosts

connect()
{
    if [ $1 ]
    then
        #Checks for  "#", spaces, and tabs to ignore them
        #Split the line in config to host and ip
        egrep -v '(^#|^\s*$|^\s*\t*#)' $CONFIG |
        while IFS="=" read -r host ip
        do 
            if [ $1 == $host ]
            then
                echo "Host $host found"
                echo "Attempting to connect to $ip"
                ssh -T $ip
                break
            else
                echo "Host doesn't exist, use -l or --list to see hosts"
            fi
        done
    fi
}

list()
{
    header=" %-10s %8s\n"
    format=" %-10s %08s\n"

    printf "$header" "HOST" "IP ADDRESS"

    #Checks for  "#", spaces, and tabs to ignore them
    #Split the line in config to host and ip
    egrep -v '(^#|^\s*$|^\s*\t*#)' $CONFIG |
    while IFS="=" read -r host ip
    do 
        printf "$format" \
        $host $ip 
    done
}

help()
{
    printf "Usage: sshcon [OPTION]... [HOST]...\n"
    printf " %s %s\t %s\n" \
    "-h," "--help" "display this help menu" \
    "-l," "--list" "show a list of the hosts from the config file"
}

while :
do
case $1 in
    -h|--help)
        help
        exit
        ;;
    -l|--list)
        list
        exit
        ;;
    -?*)
        echo "Unknown option: $1"
        break
        ;;
    *)
        if [ ! -z $1 ]
        then
            connect $1
        else
            help
        fi
        break
        ;;
esac
done



